### PR TITLE
Message typo correction

### PR DESCRIPTION
**Pull request by Bonfire**
This commit fixes a typo in the "Trade should be finalized shortly" message, as well as updates other messages sent to users. This change is very small, and most likely does not warrant its own version change

### CODE REVIEW

**Comment by idinium96** [comment]
always create a pull request to merge into `development` branch.

**Comment by idinium96** [comment]
Please also do the grammatical correction in Commands.ts > `accepttradeCommand` function.

**Comment by Bonfire** [comment]
> Please also do the grammatical correction in Commands.ts > `accepttradeCommand` function.

All set! Let me know if you catch anything else that needs to be updated.

**Comment by idinium96** [comment]
Thank you! All looks good for now. I will merge this to the development branch and will look for more

**Pull request merged**
