### PR TITLE
centralize options parsing and add testing framework

### LINKED ISSUE #142: Add testing for tf2autobot
The point of this feature is to add a useful set of tests which can be expanded upon as new features arrive. The test framework is Jest.

Current goals:

  1. Enable asserting the result of SteamUser.chatMessage() calls
  2. Centralize Option loading and default settings
  3. Add mock steam-user implementation

### PR DESCRIPTION
**Pull request by joekiller**
The point of this feature is to add a useful set of tests which can be expanded upon as new features arrive. The test framework is Jest.

  - Add Centralize Option loading and default settings
  - Add Testing of option loading

Fixes #142

### CODE REVIEW

**Comment by joekiller** [comment]
@idinium96 do you want me to rebase this onto v2?

**Comment by idinium96** [comment]
Yes, but it will be a lot of work.

**Comment by idinium96** [comment]
I can do it if you have something else to do.

**Comment by joekiller** [comment]
I'll take a look but it'll probably be 12-14 hours until I can really dig in again

**Comment by joekiller** [comment]
I'll see what I can knock out in 15 minutes right now though ;)

**Comment by idinium96** [comment]
It's okay, I think I will do this.

**Comment by joekiller** [comment]
closing for new v2-tests branch

**Pull request closed without merging**
