### PR TITLE
V2 json options

### PR DESCRIPTION
**Pull request by joekiller**
adds json formatted options

### CODE REVIEW

**Comment by joekiller** [comment]
this is ready for review

**Comment by joekiller** [comment]
I'm going to test this more. please don't merge yet

**Comment by idinium96** [comment]
> I'm going to test this more. please don't merge yet
sure thing. I've already seen some that need to be changed. I will push it soon.

**Comment by idinium96** [comment]
more to come.

**Comment by joekiller** [comment]
I'm good with this now fwiw

**Review by idinium96 — APPROVED** [review]
Looks good to me. Thank you so much!

**Comment by idinium96** [comment]
Merging...

**Pull request merged**
