### PR TITLE
add DISABLE_HIGH_VALUE_HOLD

### PR DESCRIPTION
**Pull request by joekiller**
Adds an option to allow high value items to be immediately sellable.

### CODE REVIEW

**Comment by Bonfire** [comment]
Appears to be a small change. Looks good to me!

**Review by Bonfire — APPROVED** [review]

**Comment by idinium96** [comment]
bruh please always create a pull request to the development branch.

**Review by idinium96 — APPROVED** [review]

**Comment by joekiller** [comment]
@idinium96 @Bonfire apologies for the master brach pr. Was late.

**Comment by idinium96** [comment]
> @idinium96 @Bonfire apologies for the master brach pr. Was late.

it's okay

**Pull request merged**
