### PR TITLE
V2 type updates

### PR DESCRIPTION
**Pull request by joekiller**
Add more thorough types for steam-client.

This will help with the mock interface down the line.
TradeManager still needs this treatment but that'll have to be later.

### CODE REVIEW

**Comment by joekiller** [comment]
@idinium96 this is ready for review

**Comment by idinium96** [comment]
Thanks joe, but this not includes the `steam-tradeoffer-manager` enums right?
https://github.com/idinium96/tf2autobot/blob/v2-type-updates/src/classes/Trades.ts#L46

**Comment by joekiller** [comment]
> Thanks joe, but this not includes the `steam-tradeoffer-manager` enums right?
> https://github.com/idinium96/tf2autobot/blob/v2-type-updates/src/classes/Trades.ts#L46

Yes that does address it from the perspective of running code. but it leaves the symbol for the compiler at a member  `TradeOfferManager.ETradeOfferState` that is a string vs this value is the value of ` TradeOfferManager.ETradeOfferState.Active`.  

It is very valid but the symbol is slightly different. It's getting a key from a map (what enums eventaully are) vs a property in itself.

The change is not necessary but I'd suggest we do it at some point. No immediately necessary. 

The types currently in here will help my v2-mock-handler

**Comment by idinium96** [comment]
> > Thanks joe, but this not includes the `steam-tradeoffer-manager` enums right?
> > https://github.com/idinium96/tf2autobot/blob/v2-type-updates/src/classes/Trades.ts#L46
> 
> Yes that does address it from the perspective of running code. but it leaves the symbol for the compiler at a member `TradeOfferManager.ETradeOfferState` that is a string vs this value is the value of ` TradeOfferManager.ETradeOfferState.Active`.
> 
> It is very valid but the symbol is slightly different. It's getting a key from a map (what enums eventaully are) vs a property in itself.
> 
> The change is not necessary but I'd suggest we do it at some point. No immediately necessary.
> 
> The types currently in here will help my v2-mock-handler

Oh already, then this should be fine. Final checks before merging...

**Pull request merged**
